### ISSUE TITLE
Add awareness/support for Containerfiles

### ISSUE THREAD

**Issue by DovOps** [openrewrite/rewrite-docker#3]
## What problem are you trying to solve?

Dockerfiles are the more popular container build manifest, but Containerfiles are also used with tools such as buildah and podman. 

The rewrite-docker tool should be Containerfile-aware as well.  As for whether the package needs renaming to be more inclusive of OCI containers (e.g. 'rewrite-container' or 'rewrite-container-images') can always be visited at a future time.

## Describe the solution you'd like

Add Containerfile support in this project. Practically, whatever this can do to Dockerfiles, it can do to Containerfiles. We can either modify the filename recognition to recognize both names, or create two separate classes in the assumption that their specification/adherence may diverge.

The OCI specification is listed here: https://github.com/opencontainers/image-spec/blob/main/spec.md

Docker has a 2017 blog article around the earlier emergence of the spec: https://www.docker.com/blog/demystifying-open-container-initiative-oci-specifications/

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

I'm looking to contribute this change to OpenREwrite.

**Comment by timtebeek** [comment]
Thanks for logging this improvement! From looking at the code we'd only have to change this matcher when starting out:
https://github.com/openrewrite/rewrite-docker/blob/b69bd42aad35804036dd8160722ee19d02eac1bc/src/main/java/org/openrewrite/docker/trait/Dockerfile.java#L54

From the types of changes we're making here for now I think we're fine to treat Dockerfiles and Containerfiles as if they were the same. Once those diverge we can reevaluate, and indeed potentially rename or clone recipes as needed. It's well possible this will look different in the future if we are to add a proper parser.

We'll likely want to make matching changes to our OSS plugins and Moderne CLI to parse Container files as plain text too.
1. https://github.com/openrewrite/rewrite-maven-plugin/blob/1d2d8aa4ac246e7b0d47d3b4762c96379cb7ee92/src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java#L125
2. https://github.com/openrewrite/rewrite-gradle-plugin/blob/5632d165c0c0660912d4fadad996d8dfc12a70e2/plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java#L312

Note how each of those use `"**/Dockerfile*"`; would we want to extend that optional suffix matcher for container files here too?

**Comment by DovOps** [comment]
@timtebeek  this was my thinking as well, and I was planning on submitting that (Along with unit tests which test that containerfile is recognized).  

>Note how each of those use "**/Dockerfile*"; would we want to extend that optional suffix matcher for container files here too?

I'd think we'd want to find Containerfiles wherever we find Dockerfiles, so I'd say yes.

I'll submit a PR for the simple change.
